import * as Fa from 'react-icons/fa';
import * as Mui from '@mui/icons-material';
import * as FaPro from '@fortawesome/free-solid-svg-icons';

export const icons = {
    search: Fa.FaSearch,
    password: Mui.SyncLock,
    calendar: Mui.Event,
    school: Mui.AccountBalance,
    list: Mui.ViewList,
    folder: Mui.Folder,
    bag: Mui.ShoppingBag,
    users: Mui.People,
    idCard: Fa.FaIdCard,
    phone: Mui.Phone,
    vaccine: Mui.Vaccines,
    logout: Mui.Logout,
    warning: Mui.Warning,
    delete: Mui.Delete,
    close: Mui.Close,
    status: Mui.PowerSettingsNewRounded,
    email: Mui.AlternateEmailRounded,
    person: Mui.PersonRounded,
    iphone: Mui.PhoneIphoneRounded,
    phoneRounded: Mui.PhoneRounded,
    user: Fa.FaUserSecret,
    userName: Fa.FaHatCowboy,
    tag: Fa.FaUserTag,
    editOff: Mui.EditOffRounded,
    edit: Mui.EditRounded,
    filePdf: Fa.FaFilePdf,
    fileWord: Fa.FaFileWord,
    fileExcel: Fa.FaFileExcel,
    filePowerpoint: Fa.FaFilePowerpoint,
    fileArchive: Fa.FaFileArchive,
    fileImage: Fa.FaFileImage,
    fileVideo: Fa.FaFileVideo,
    file: Fa.FaFile,
    inBox: Mui.InboxOutlined,
    add: Mui.Add,
    more: Mui.MoreHoriz,
    arrowBack: Mui.ArrowBackIosRounded,
    ArrowBackNew: Mui.ArrowBackIosNewRounded,
    arrowDropDown: Mui.ArrowDropDown,
    arrowForward: Mui.ArrowForwardIosRounded,
    info:Mui.InfoOutlined,
    place: Mui.PlaceOutlined,
    calendarToday: Mui.CalendarTodayRounded,
    share: Mui.ShareRounded,
    contactPhone: Mui.ContactPhoneOutlined,
    visibility: Mui.VisibilityOutlined,
    straighten: Mui.StraightenOutlined,
    soap: Mui.SoapOutlined,
    headphones: Mui.HeadphonesOutlined,
    alarm: Mui.AlarmOutlined,
    support: Mui.ContactSupportRounded,
    systemAdmin:FaPro.faUserNinja,

    schoolPrincipal: FaPro.faUserTie,

    healthCoordinator: FaPro.faUserMd,
    schoolContact: FaPro.faUserCircle,

    userMd: FaPro.faUserMd,
    launch: Mui.LaunchRounded,
    moreVert: Mui.MoreVertRounded
};
